# Generated by Django 5.0.6 on 2024-05-24 00:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('idade', models.IntegerField()),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('quartos', models.CharField(max_length=50)),
            ],
        ),
    ]
