# Generated by Django 5.0.6 on 2024-05-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendamento', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salas', models.CharField(max_length=50)),
                ('numero', models.IntegerField(max_length=2)),
                ('descricao', models.TextField(max_length=255)),
                ('equipamentos', models.CharField(max_length=50)),
                ('corredor', models.CharField(max_length=50)),
            ],
        ),
    ]
