# Generated by Django 5.0.6 on 2024-05-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendamento', '0003_salas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salas',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
