# Generated by Django 5.0.6 on 2024-05-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendamento', '0004_alter_salas_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salas',
            name='descricao',
            field=models.TextField(max_length=50),
        ),
    ]
