# Generated by Django 5.0.6 on 2024-06-04 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agendamento', '0006_salas_agendado_por_salas_agendamento_salas_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salas',
            name='corredor',
        ),
        migrations.RemoveField(
            model_name='salas',
            name='numero',
        ),
    ]
