# Generated by Django 5.0.6 on 2024-06-09 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendamento', '0007_remove_salas_corredor_remove_salas_numero'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salas',
            name='agendado_por',
        ),
        migrations.RemoveField(
            model_name='salas',
            name='agendamento',
        ),
        migrations.RemoveField(
            model_name='salas',
            name='horario',
        ),
        migrations.CreateModel(
            name='Agendamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_da_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira')], max_length=10)),
                ('periodo', models.CharField(choices=[('manhaA', 'Manhã A'), ('manhaB', 'Manhã B'), ('tardeA', 'Tarde A'), ('tardeB', 'Tarde B'), ('noiteA', 'Noite A')], max_length=10)),
                ('agendado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Agendamento.salas')),
            ],
            options={
                'unique_together': {('sala', 'dia_da_semana', 'periodo')},
            },
        ),
    ]
