# Generated by Django 5.0.6 on 2024-06-09 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agendamento', '0008_remove_salas_agendado_por_remove_salas_agendamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentos',
            name='agendado_por',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
